### ISSUE TITLE
Needing a better way to set the config of each room

### ISSUE THREAD

**Issue by sunnyadn** [Mogara/Cardirector#4]
1. More parameters should be declared, so that the owner could access the room config such as the room capacity.
2. The way to pack basic settings should not be exposed to users. The users just need to pack the advanced config related to their game logic themselves. i.e. the declaration looks like the following case. 

``` c++
CServer::createRoom(const CServerPlayer *player, const QString &name, uint capacity, const QVariant & logicConfig)
```

If there are too many basic settings, we can also declare a config structure.

**Comment by takashiro** [comment]
或许可以让App自己在GameLogic中调用CServerPlayer::AddCallback来增加一个新的网络指令来配置GameLogic。这样可以完全避开QVariant。分开两条指令还便于创建房间之后修改游戏配置。
